import { Product } from "./product";
import { User } from "./user";

export interface Order {
  id?: number; // Optional because it's generated by the backend
  date: Date;
  status: string;
  user: User;
  products:Product[];

}
